const SCREENWIDTH = 650, SCREENHEIGHT = 600
const GROUNDHEIGHT = 50, GRASSHEIGHT = 20
 const BIRDWIDTH = 50, BIRDHEIGHT = 35
 const COLUMNWIDTH = 100, COLUMNBOTTOM = GROUNDHEIGHT+GRASSHEIGHT, COLUMNLEFT = SCREENWIDTH/2
 const HOLEHEIGHT = 125
 const FLYINGSPACE = SCREENHEIGHT - GROUNDHEIGHT - GRASSHEIGHT
 const SOARDIST = 40, FALLDIST = 5
 const gameOver = {
 top: SCREENHEIGHT/2-200, 
 left: SCREENWIDTH/2-180
}
 const gameOverScore = {
 top: SCREENHEIGHT/2-150, 
 left: SCREENWIDTH/2-160
}
 const playingScore = {
 top: 0,
 left: SCREENWIDTH/2-160
}

export {
 SCREENHEIGHT, SCREENWIDTH, 
 GRASSHEIGHT, GROUNDHEIGHT,
 BIRDHEIGHT, BIRDWIDTH,
 COLUMNBOTTOM, COLUMNLEFT, COLUMNWIDTH, 
 HOLEHEIGHT,
 FLYINGSPACE,
 SOARDIST,
 FALLDIST,
 gameOver,
 gameOverScore,
 playingScore
}